name: Security audit
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-deny

      - name: Debug file existence
        run: ls -la .cargo && cat .cargo/deny.toml || echo "deny.toml not found"

      - name: Scan for vulnerabilities
        run: cargo deny --config .cargo/deny.toml check advisories